import type { Metadata } from 'next';
import { PokemonContextProvider } from './context/pokemon';
import './globals.css';

export const metadata: Metadata = {
  title: 'Pokedex',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <PokemonContextProvider>{children}</PokemonContextProvider>
      </body>
    </html>
  );
}
